### ISSUE TITLE
score

### ISSUE THREAD

**Issue by dvpaa** [dvpaa/space-invaders#2]
- [x] 스코어 기준 세우기
- [x] 게임 화면에 현재 스코어 표시하기
- [x] 스테이지 종료시 최종 스코어 표시하기

**Comment by Leesowon** [comment]
일정 시간 안에 클리어하면 최대 점수 부여
이후 시간부터는 2초당 3점 마이너스
클리어하기만 하면 10점 부여
하다가 죽으면 점수 없음
